language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update
    - sudo apt-get install pandoc

install:
    - pip install -e .

script: python test.py --c config.ini

after_failure: echo "Test failed"

